/** Generated by drizzle-kit; the actual content is loaded via Metro inline-import. */
declare const migrations: {
  journal: { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] };
  migrations: Record<string, string>;
};
export default migrations;
